version: 2.1
orbs:
  architect: giantswarm/architect@5.6.0

workflows:
  package-and-push-chart-on-tag:
    jobs:
      - architect/push-to-registries:
          context: architect
          name: push-to-registries
          filters:
            tags:
              only: /^v.*/
