name: build-and-deploy
run-name: ${{ github.actor }} is building and deploying
on:
  release:
    types: [published]
jobs:
  push_to_registry:
    name: Publish to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: ${{ matrix.platforms }}
          tags: giantswarm/staticjscms-hugo-standalone:${{ release.tag_name }}
          push: true
          outputs: type=image,name=giantswarm/staticjscms-hugo-standalone:${{ release.tag_name }}
